listofVMs:
  - name: My1stvm   
    os_type: Linux
    sku_name: P1v2
  - name: My2ndvm 
    os_type: Linux
    sku_name: P1v2

windowsapplist:
  - name: firstwindowsapp    
    os_type: Windows
    sku_name: P5mv3
  - name: secondwindowsapp    
    os_type: Windows
    sku_name: P5mv3
  - name: thirdwindowsapp    
    os_type: Windows
    sku_name: P5mv3
